DROP PROCEDURE add_category;
DROP PROCEDURE add_owner;
DROP PROCEDURE add_pet;
DROP TABLE Administrators CASCADE;
DROP TABLE isPaidSalaries CASCADE;
DROP TABLE ownsPets CASCADE;
DROP TABLE Users CASCADE;
DROP TABLE Caretakers CASCADE;
DROP TABLE Owners CASCADE;
DROP TABLE Categories CASCADE;
DROP TABLE Bids CASCADE;
DROP TABLE timings CASCADE;
DROP TABLE CHARGES CASCADE;
drop table declares_availabilities;
drop trigger merge_availabilities;
drop trigger check_deletable;
drop trigger update_availabilities;