DROP TABLE IF EXISTS cp_payment;
DROP TABLE IF EXISTS cp_passenger_rates;
DROP TABLE IF EXISTS cp_driver_rates;
DROP TABLE IF EXISTS cp_journey_occurs;
DROP TABLE IF EXISTS cp_passenger_bid;
DROP TABLE IF EXISTS cp_advertised_journey;
DROP TABLE IF EXISTS cp_payment_method;
DROP TABLE IF EXISTS cp_driver_drives;
DROP TABLE IF EXISTS cp_passenger CASCADE;
DROP TABLE IF EXISTS cp_driver CASCADE;
DROP TABLE IF EXISTS cp_user CASCADE;
